const T = {
    ru: {
        _meta: { title: "MetaFrame — Кино × ИИ × Маркетинг", htmlLang: "ru", recCity: "Nazarbayev University · Astana" },
        "nav.about": "О нас", "nav.services": "Услуги", "nav.academy": "Академия", "nav.contacts": "Контакты", "nav.cta": "Запросить смету →",
        "hero.idx": "Index · 01",
        "hero.tagline": "Cinema × AI × Marketing",
        "hero.title": '<span class="line">Производство</span><span class="line">визуала <span class="symbol">∞</span></span><span class="line">нового <span class="accent">формата</span></span>',
        "hero.subtitle": 'Кинематограф <span class="accent">×</span> ИИ <span class="accent">×</span> Маркетинг — в одной производственной системе.',
        "hero.cta1": "Смотреть работы", "hero.cta2": "Обсудить проект", "hero.cta3": "Академия", "hero.scroll": "Скролл",
        "founder.eyebrow": "Основатель · 02",
        "founder.title": 'Кто стоит<br>за <span style="color:var(--cyan); font-style: italic;">кадром</span>',
        "founder.role": "Основатель · Креативный директор",
        "founder.name": "Дархан<br>Телманов",
        "founder.position": "Руководитель академии MetaFrame",
        "founder.stat1.lbl": "Опыт", "founder.stat1.val": "Кино / реклама / AI",
        "founder.stat2.lbl": "Был",
        "founder.stat3.val": "Самый быстрорастущий AI-стартап в мире",
        "founder.stat4.lbl": "Геогр.",
        "founder.p1": 'MetaFrame — студия визуального продакшна на нейросетях. Работаем с брендами по всему миру: <strong>имиджевые ролики, соц-креативы под таргет, LED-контент, key&nbsp;visuals кампаний</strong>.',
        "founder.p2": 'Основатель — <strong>Дархан Телманов</strong>. До MetaFrame — <span class="highlight">Creative Director в higgsfield.ai</span>, формировал визуальный язык продукта, которым пользуются миллионы креаторов и брендов.',
        "founder.p3": 'Мы соединяем <strong>кинематографический подход</strong> — композиция, свет, ритм монтажа — с <strong>инженерным пайплайном</strong> производства. Нейросети — инструмент, не заменитель идеи.',
        "founder.quote": '«ИИ генерировать может каждый.<br>Но <span style="color:var(--cyan)">режиссировать</span> — единицы.»',
        "pillars.eyebrow": "Подход · 03", "pillars.meta": "Почему MetaFrame",
        "pillars.title": 'Три принципа,<br>которые меняют <span style="color:var(--cyan); font-style: italic;">правила</span>',
        "pillars.lede": "Мы переписали логику видеопроизводства. Никаких командировок, актёров на смене, бесконечных согласований локаций. Только результат — и в десятки раз быстрее.",
        "pillars.p1.title": "Не нужно физически присутствовать",
        "pillars.p1.text": "Мы работаем с брендами из любой точки мира удалённо. Не нужно лететь на смену, организовывать локацию, собирать команду в одной стране. Концепт, продакшн, финальная сдача — всё в облаке.",
        "pillars.p2.title": "Реальная сцена 1&nbsp;к&nbsp;1 — по фото",
        "pillars.p2.text": "Хотите воссоздать ваш магазин, продукт, цех, ивент-площадку или сотрудников? Достаточно прислать нам качественные фотографии — мы повторим обстановку, лица и фирменный стиль точно, без потери узнаваемости.",
        "pillars.p3.title": "В&nbsp;10 раз быстрее съёмки",
        "pillars.p3.text": "Имиджевый ролик за день вместо двух недель. Десятки таргет-креативов за смену вместо месяца. Бесконечные итерации без переплат за смену, технику и логистику.",
        "clip.tag": "Имиджевые клипы · 16:9",
        "clip.title": 'Имиджевые<br><span class="accent">клипы</span>',
        "clip.desc": "Premium-ролики для брендов: открытие магазина, презентация продукта, фирменный имиджевый материал, корпоративные истории. Кинематографичный язык — без съёмочного дня.",
        "social.tag": "Соц-сети · 9:16 · Креативы под таргет",
        "social.title": 'Формат<br><span class="accent">соц-сетей</span>',
        "social.desc": "Reels, TikTok, Shorts, Stories. Креативы под таргетированную рекламу для Meta, TikTok Ads, YouTube Shorts. Производим десятки версий одного оффера для A/B-тестов и масштабирования закупки.",
        "social.callout": '<span class="strike">Снимать</span><br><span class="accent">Бесконечно</span><br>итерировать',
        "social.r1.lbl": "Скорость", "social.r1.val": "×10 быстрее съёмки",
        "social.r2.lbl": "Объём", "social.r2.val": "30+ креативов / неделя",
        "social.r3.lbl": "A/B-тесты", "social.r3.val": "Без перезаездов",
        "social.r4.lbl": "Стоимость", "social.r4.val": "От стандартного съёмочного дня",
        "social.r5.lbl": "Языки", "social.r5.val": "Любые рынки и аудитории",
        "poster.tag": "OOH · Постеры · Ключевой визуал",
        "poster.title": 'Постеры и<br><span class="accent">key&nbsp;visual</span>',
        "poster.desc": "Большие баннеры, наружная реклама, афиши для мероприятий, обложки кампаний, ключевой визуал года для бренда. Производим в любом разрешении под любой формат — от листовки до билборда в Time Square.",
        "poster.uc1": "Билборды 6×3", "poster.uc2": "Городская реклама", "poster.uc3": "Афиши",
        "poster.uc4": "Концерты / Туры", "poster.uc5": "Mall-баннеры", "poster.uc6": "Outdoor-кампании",
        "poster.uc7": "Обложки для соц-сетей", "poster.uc8": "Спортивные ивенты", "poster.uc9": "Транзитная реклама",
        "led.tag": "LED · Сцена · Ивенты",
        "led.title": 'Анимации<br>для&nbsp;<span class="accent">сцены</span>',
        "led.desc": "Анимированный визуал для LED-экранов на концертах, фестивалях, корпоративных мероприятиях, конференциях. Зацикленные сцены под ритм выступления, имиджевые лупы под бренд, генеративные паттерны.",
        "led.uc1": "Концерты", "led.uc2": "Фестивали", "led.uc3": "Конференции", "led.uc4": "Корпоративы",
        "led.uc5": "Презентации", "led.uc6": "Свадьбы premium", "led.uc7": "Спорт-мероприятия", "led.uc8": "Подиум / fashion",
        "photo.tag": "Product · Fashion · Lifestyle",
        "photo.title": 'Фотосеты<br>продуктов<br>и&nbsp;<span class="accent">одежды</span>',
        "photo.desc": "Каталоги, lookbook'и, lifestyle-снимки, контент для маркетплейсов. Любая локация, любой свет, любая модель — без поездки в студию. Достаточно фотографий товара — мы создадим продакшн-качество.",
        "ext.eyebrow": "Ещё · 09", "ext.meta": "Что ещё мы умеем",
        "ext.title": 'Дополнительные<br><span style="color:var(--cyan); font-style: italic;">возможности</span>',
        "ext.lede": "Кроме основных форматов, MetaFrame закрывает целый ряд задач, о которых клиенты часто узнают уже после первой встречи. Если есть визуальный кадр — мы найдём способ его сделать.",
        "ext.i1.t": "AI-аватары / цифровые амбассадоры",
        "ext.i1.d": "Цифровой двойник директора, актёра или модели. Один раз обучили — снимаемся в десятках роликов без личного присутствия.",
        "ext.i2.t": "Музыкальные клипы и визуал для артистов",
        "ext.i2.d": "Полноценные клипы, тизеры, обложки треков, визуал на стриминг. От инди до major-релизов.",
        "ext.i3.t": "Контент для маркетплейсов",
        "ext.i3.d": "Wildberries, Ozon, Amazon, Wayfair: главные фото, инфографика, 360°, видеоразвороты, lifestyle.",
        "ext.i4.t": "Анимированные логотипы и intro",
        "ext.i4.d": "Brand bumpers, motion-логотипы, заставки для YouTube, корпоративных видео, мероприятий.",
        "ext.i5.t": "3D-визуализация и архитектура",
        "ext.i5.d": "Интерьеры для застройщиков, отелей, ресторанов. Фасады, экстерьеры, кадры будущего объекта.",
        "ext.i6.t": "Локализация под рынки",
        "ext.i6.d": "Один креатив — десятки версий под язык, внешность, культуру. Идеально для международных кампаний.",
        "ext.i7.t": "Storyboards и пре-визуализация",
        "ext.i7.d": "Раскадровки и pre-viz для будущих живых съёмок: режиссёру и продюсеру — точно видеть кадр заранее.",
        "ext.i8.t": "Контент-пакеты под подписку",
        "ext.i8.d": "«30 reels за неделю», «контент-план на месяц за день». Бренд получает поток креатива под постоянный продакшн.",
        "course.eyebrow": "Академия · 10",
        "course.meta": "MetaFrame Academy",
        "course.title": 'От нуля до <span style="color:var(--cyan);font-style:italic">AI-креатора</span><br>за 6 недель',
        "course.lede": "6 модулей, 80% практики, готовое портфолио и шанс попасть в команду MetaFrame.",
        "course.s1": "недель", "course.s2": "модулей", "course.s3": "практика / теория", "course.s4": "первый клиент",
        "course.teaser_cta": "Узнать больше",
        "course.m1.tag": "Фундамент",
        "course.m1.title": "Из хаоса генераций — в систему, которая даёт результат с первого промпта",
        "course.m1.b1": "Перестаёшь угадывать промпты — начинаешь управлять результатом",
        "course.m1.b2": "Разбираешься, как ИИ создаёт генерации и где у него тонкости",
        "course.m1.b3": "Понимаешь, какой инструмент под какую задачу — без метаний между 15 сервисами",
        "course.m1.b4": "Читаешь чужие работы как рентген — видишь не картинку, а пайплайн за ней",
        "course.m2.tag": "Фото · Промпт-инжиниринг",
        "course.m2.title": "Фотосессия, которой не было. Студия, которая не существует. Результат, который не отличить.",
        "course.m2.b1": "Меняешь погоду, объект, локацию — без потери стиля",
        "course.m2.b2": "Генерируешь fashion-фотосессии без студии, модели и фотографа",
        "course.m2.b3": "Собираешь продуктовые карточки для e-commerce неотличимо от профи-съёмки",
        "course.m2.b4": "Держишь единого персонажа на 50+ кадров — одно лицо, один стиль",
        "course.m2.b5": "Управляешь камерой через текст — фокус, ГРИП, схема света, всё промптом",
        "course.m3.tag": "Видео · Сценаристика",
        "course.m3.title": "Анимируешь одним промптом то, что раньше требовало After Effects и неделю работы",
        "course.m3.b1": "Пишешь сценарии под логику нейросетей — то, что модель реально отрендерит",
        "course.m3.b2": "Анимируешь сложные сцены: несколько объектов, взаимодействие, контакт",
        "course.m3.b3": "Управляешь камерой как оператор — через текстовые команды",
        "course.m3.b4": "Держишь персонажа и локацию от первого кадра до последнего — без «дрифта»",
        "course.m3.b5": "Раскладываешь действие по секундам, а не надеешься на случайный результат",
        "course.m4.tag": "Саунд-дизайн · SFX",
        "course.m4.title": "Без звука — демка. Со звуком — продакшн. Разница — этот модуль.",
        "course.m4.b1": "Генерируешь музыку под настроение сцены — описываешь текстом, получаешь готовое",
        "course.m4.b2": "Синхронизируешь звук с движением губ в кадре (lip-sync)",
        "course.m4.b3": "Клонируешь голос — управляешь интонацией, паузами, эмоцией без диктора",
        "course.m4.b4": "Убираешь «пластиковое» AI-звучание — комната, реверб, фон — голос садится в сцену",
        "course.m4.b5": "Делаешь полноценные треки и ремиксы популярных песен",
        "course.m5.tag": "Монтаж · Колор",
        "course.m5.title": "Сгенерировать отрывки может каждый — смонтировать в цельную картину единицы",
        "course.m5.b1": "Сводишь клипы из разных моделей в один визуальный стиль — без скачков цвета и контраста",
        "course.m5.b2": "Выравниваешь тайминг и ритм — монтаж перестаёт быть обрывистым",
        "course.m5.b3": "Колор-грейдингом вытягиваешь «пластиковую» AI-картинку до кинематографа",
        "course.m5.b4": "Убираешь артефакты генерации на постпродакшне — зритель не замечает, что это AI",
        "course.m5.b5": "Апскейлишь до 4K без потери деталей — Topaz, кодеки, настройки экспорта",
        "course.m6.tag": "Портфолио · Выход в рынок",
        "course.m6.title": "Закрываешь первого клиента за 2 недели — с готовым оффером, портфолио и скриптом",
        "course.m6.b1": "Собираешь 5 роликов под разные ниши — e-commerce, рестораны, недвижимость, fashion, личный бренд",
        "course.m6.b2": "Выстраиваешь воронку от первого касания до оплаты — холодное, созвон, оффер, закрытие",
        "course.m6.b3": "Пишешь скрипты для переписки и созвонов — знаешь, что отвечать на «а что я получу» и «почему так дорого»",
        "course.m6.b4": "Упаковываешь страницу так, чтобы она продавала за тебя",
        "course.method": 'Все модули идут <strong>в перемешку, начиная с первого урока</strong> — курс направлен на то, чтобы вы скорее начали практиковаться, привыкали к ИИ и нарабатывали свой стиль. <strong>80% практики, 20% теории.</strong>',
        "course.bonus.tag": "Главный бонус",
        "course.bonus.title": 'Отбор в <span style="color:var(--cyan)">MetaFrame</span>',
        "course.bonus.desc": "Мы ищем таланты. Автор лучшего финального ролика получает оффер на оплачиваемую стажировку или проектную работу в нашей студии — над реальными заказами для брендов.",
        "course.cta": "Подать заявку",
        "course.back_to_main": "← На главную",
        "stats.s1": "Быстрее, чем классическая съёмка",
        "stats.s2": "Командировок и съёмочных групп",
        "stats.s3": "Итераций и адаптаций без передоплат",
        "stats.s4": "Работаем с любым часовым поясом",
        "cta.eyebrow": "Поработаем · 11",
        "cta.title": 'Расскажите<br>про&nbsp;<span class="accent">проект</span>',
        "cta.sub": "Мы работаем с брендами по всему миру. Опишите задачу — мы вернёмся с концептом, сроком и сметой в течение 24 часов.",
        "cta.button": "Написать на почту",
        "cta.studio_lbl": "Студия",
        "footer.founded": "Основано Дарханом Телмановым"
    },
    en: {
        _meta: { title: "MetaFrame — Cinema × AI × Marketing", htmlLang: "en", recCity: "Nazarbayev University · Astana" },
        "nav.about": "About", "nav.services": "Services", "nav.academy": "Academy", "nav.contacts": "Contact", "nav.cta": "Request a quote →",
        "hero.idx": "Index · 01",
        "hero.tagline": "Cinema × AI × Marketing",
        "hero.title": '<span class="line">Cinematic</span><span class="line">visuals <span class="symbol">∞</span></span><span class="line">re<span class="accent">invented</span></span>',
        "hero.subtitle": 'Cinema <span class="accent">×</span> AI <span class="accent">×</span> Marketing — fused into a single production system.',
        "hero.cta1": "See the work", "hero.cta2": "Discuss a project", "hero.cta3": "Academy", "hero.scroll": "Scroll",
        "founder.eyebrow": "Founder · 02",
        "founder.title": 'Who stands<br>behind the <span style="color:var(--cyan); font-style: italic;">frame</span>',
        "founder.role": "Founder · Creative Director",
        "founder.name": "Darkhan<br>Telmanov",
        "founder.position": "Head of MetaFrame Academy",
        "founder.stat1.lbl": "Experience", "founder.stat1.val": "Film / advertising / AI",
        "founder.stat2.lbl": "Was",
        "founder.stat3.val": "The fastest-growing AI startup in the world",
        "founder.stat4.lbl": "Geo",
        "founder.p1": 'MetaFrame is a visual production studio built on generative AI. We deliver <strong>brand films, paid-ads creatives, LED content and campaign key&nbsp;visuals</strong> for global brands.',
        "founder.p2": 'Founded by <strong>Darkhan Telmanov</strong>. Previously <span class="highlight">Creative Director at higgsfield.ai</span>, where he shaped the visual language of a product now used by millions of creators and brands.',
        "founder.p3": 'We combine <strong>cinematic craft</strong> — composition, light, editing rhythm — with an <strong>engineered production pipeline</strong>. AI is a tool, not a substitute for the idea.',
        "founder.quote": '"Anyone can generate with AI.<br>Only a few can <span style="color:var(--cyan)">direct</span> it."',
        "pillars.eyebrow": "Approach · 03", "pillars.meta": "Why MetaFrame",
        "pillars.title": 'Three principles<br>that rewrite the <span style="color:var(--cyan); font-style: italic;">rules</span>',
        "pillars.lede": "We rebuilt the logic of video production from the ground up. No travel, no actors on call sheets, no endless location approvals. Just results — many times faster.",
        "pillars.p1.title": "No physical presence required",
        "pillars.p1.text": "We work with brands from anywhere in the world, fully remote. No flights, no location scouting, no need to assemble a crew in one country. Concept, production, final delivery — all in the cloud.",
        "pillars.p2.title": "Real scenes 1&nbsp;to&nbsp;1 — from photos",
        "pillars.p2.text": "Want to recreate your store, product, factory floor, event venue, or team members? Send us high-quality photos and we'll reproduce the setting, the faces, and the brand identity precisely — without losing recognizability.",
        "pillars.p3.title": "10×&nbsp;faster than shooting",
        "pillars.p3.text": "An image film in a day instead of two weeks. Dozens of paid-ads creatives in a day instead of a month. Endless iterations with no extra charges for shoot days, equipment, or logistics.",
        "clip.tag": "Brand films · 16:9",
        "clip.title": 'Brand<br><span class="accent">films</span>',
        "clip.desc": "Premium films for brands: store openings, product launches, brand image pieces, corporate stories. Cinematic language — without a single shoot day.",
        "social.tag": "Social · 9:16 · Paid-ads creatives",
        "social.title": 'Social<br><span class="accent">format</span>',
        "social.desc": "Reels, TikTok, Shorts, Stories. Creatives built for paid ads on Meta, TikTok Ads, YouTube Shorts. We produce dozens of versions of a single offer for A/B testing and ad-buying scale.",
        "social.callout": '<span class="strike">Shoot</span><br><span class="accent">Iterate</span><br>endlessly',
        "social.r1.lbl": "Speed", "social.r1.val": "10× faster than shooting",
        "social.r2.lbl": "Volume", "social.r2.val": "30+ creatives / week",
        "social.r3.lbl": "A/B tests", "social.r3.val": "No re-shoots",
        "social.r4.lbl": "Cost", "social.r4.val": "From a single shoot-day rate",
        "social.r5.lbl": "Languages", "social.r5.val": "Any market, any audience",
        "poster.tag": "OOH · Posters · Key visual",
        "poster.title": 'Posters &<br><span class="accent">key&nbsp;visual</span>',
        "poster.desc": "Large-format banners, outdoor advertising, event posters, campaign covers, the year's key visual for your brand. Produced at any resolution for any format — from flyer to Times Square billboard.",
        "poster.uc1": "Billboards 6×3", "poster.uc2": "City advertising", "poster.uc3": "Event posters",
        "poster.uc4": "Concerts / tours", "poster.uc5": "Mall banners", "poster.uc6": "Outdoor campaigns",
        "poster.uc7": "Social covers", "poster.uc8": "Sports events", "poster.uc9": "Transit ads",
        "led.tag": "LED · Stage · Event",
        "led.title": 'Animations<br>for the&nbsp;<span class="accent">stage</span>',
        "led.desc": "Animated visuals for LED screens at concerts, festivals, corporate events, conferences. Loop-ready scenes timed to the performance, brand image loops, generative patterns.",
        "led.uc1": "Concerts", "led.uc2": "Festivals", "led.uc3": "Conferences", "led.uc4": "Corporate events",
        "led.uc5": "Keynotes", "led.uc6": "Premium weddings", "led.uc7": "Sporting events", "led.uc8": "Runway / fashion",
        "photo.tag": "Product · Fashion · Lifestyle",
        "photo.title": 'Product<br>and fashion<br><span class="accent">photo&nbsp;sets</span>',
        "photo.desc": "Catalogues, lookbooks, lifestyle imagery, marketplace content. Any location, any lighting, any model — without traveling to a studio. Send us product photos and we'll deliver production-grade results.",
        "ext.eyebrow": "More · 09", "ext.meta": "What else we do",
        "ext.title": 'Additional<br><span style="color:var(--cyan); font-style: italic;">capabilities</span>',
        "ext.lede": "Beyond the core formats, MetaFrame handles a whole range of work that clients often only learn about after the first meeting. If a shot can be visualized — we'll find a way to make it.",
        "ext.i1.t": "AI avatars / digital ambassadors",
        "ext.i1.d": "A digital twin of a CEO, actor, or model. Trained once — then appears in dozens of clips without needing to be on set.",
        "ext.i2.t": "Music videos and visuals for artists",
        "ext.i2.d": "Full music videos, teasers, track covers, streaming visuals. From indie releases to majors.",
        "ext.i3.t": "Marketplace content",
        "ext.i3.d": "Wildberries, Ozon, Amazon, Wayfair: hero images, infographics, 360°, video reveals, lifestyle.",
        "ext.i4.t": "Animated logos and intros",
        "ext.i4.d": "Brand bumpers, motion logos, intros for YouTube, corporate videos, and live events.",
        "ext.i5.t": "3D visualization & architecture",
        "ext.i5.d": "Interiors for developers, hotels, restaurants. Facades, exteriors, future-state renders of any space.",
        "ext.i6.t": "Localization for new markets",
        "ext.i6.d": "One creative — dozens of versions tailored to language, appearance, culture. Ideal for international campaigns.",
        "ext.i7.t": "Storyboards & pre-visualization",
        "ext.i7.d": "Storyboards and pre-viz for upcoming live shoots: directors and producers see every shot before going to set.",
        "ext.i8.t": "Subscription content packs",
        "ext.i8.d": '"30 reels a week", "a month of content in a day". Brands receive a steady flow of creatives for always-on production.',
        "course.eyebrow": "Academy · 10",
        "course.meta": "MetaFrame Academy",
        "course.title": 'From zero to <span style="color:var(--cyan);font-style:italic">AI creator</span><br>in 6 weeks',
        "course.lede": "6 modules, 80% practice, a real portfolio, and a shot at joining the MetaFrame team.",
        "course.s1": "weeks", "course.s2": "modules", "course.s3": "practice / theory", "course.s4": "first client",
        "course.teaser_cta": "Learn more",
        "course.m1.tag": "Foundation",
        "course.m1.title": "From the chaos of generations into a system that delivers from the first prompt",
        "course.m1.b1": "Stop guessing prompts — start steering the result",
        "course.m1.b2": "Understand how AI builds generations and where its quirks live",
        "course.m1.b3": "Pick the right tool for the job — stop jumping between 15 services",
        "course.m1.b4": "Read other people's work like an x-ray — see the pipeline, not just the picture",
        "course.m2.tag": "Photo · Prompt engineering",
        "course.m2.title": "A photoshoot that never happened. A studio that doesn't exist. A result you can't tell apart.",
        "course.m2.b1": "Change the weather, the object, the location — without losing the style",
        "course.m2.b2": "Generate fashion shoots without a studio, model, or photographer",
        "course.m2.b3": "Build e-commerce product cards indistinguishable from pro shoots",
        "course.m2.b4": "Hold a single character across 50+ frames — one face, one style",
        "course.m2.b5": "Direct the camera through text — focus, DoF, lighting — all by prompt",
        "course.m3.tag": "Video · Scripting",
        "course.m3.title": "Animate with one prompt what used to require After Effects and a week of work",
        "course.m3.b1": "Write scripts that match how neural networks actually render",
        "course.m3.b2": "Animate complex scenes: multiple objects, interaction, contact",
        "course.m3.b3": "Direct the camera like a DP — through text commands",
        "course.m3.b4": "Hold a character and location from first frame to last — no drift",
        "course.m3.b5": "Break the action down second by second instead of hoping for a lucky take",
        "course.m4.tag": "Sound design · SFX",
        "course.m4.title": "Without sound — it's a demo. With sound — it's production. That's this module.",
        "course.m4.b1": "Generate music for the mood of a scene — describe it in text, get it back",
        "course.m4.b2": "Sync audio to on-screen mouth movement (lip-sync)",
        "course.m4.b3": "Clone voices — control intonation, pauses, emotion, no booth needed",
        "course.m4.b4": "Strip the plastic AI sound — room tone, reverb, ambience — voices sit in the scene",
        "course.m4.b5": "Build full tracks and remixes of popular songs",
        "course.m5.tag": "Edit · Color",
        "course.m5.title": "Anyone can generate clips — turning them into a coherent piece is rare",
        "course.m5.b1": "Match clips from different models into one visual style — no color or contrast jumps",
        "course.m5.b2": "Level the timing and rhythm — your edit stops feeling choppy",
        "course.m5.b3": "Use color grading to pull plastic AI footage up to cinematic levels",
        "course.m5.b4": "Clean up generation artifacts in post — the viewer never notices it's AI",
        "course.m5.b5": "Upscale to 4K without losing detail — Topaz, codecs, export settings",
        "course.m6.tag": "Portfolio · Going to market",
        "course.m6.title": "Close your first client in 2 weeks — with an offer, a portfolio and a sales script",
        "course.m6.b1": "Build 5 reels for different niches — e-commerce, restaurants, real estate, fashion, personal brand",
        "course.m6.b2": "Build a funnel from first touch to payment — cold message, call, offer, close",
        "course.m6.b3": "Write scripts for DMs and calls — know what to say to \"what do I get\" and \"why so expensive\"",
        "course.m6.b4": "Package your page so it sells for you",
        "course.method": 'All modules run <strong>interleaved from lesson one</strong> — the course is designed so you start practicing fast, get comfortable with AI, and build your own style. <strong>80% practice, 20% theory.</strong>',
        "course.bonus.tag": "Main bonus",
        "course.bonus.title": 'Selection into <span style="color:var(--cyan)">MetaFrame</span>',
        "course.bonus.desc": "We're hiring talent. The author of the best final reel gets an offer for a paid internship or project work in our studio — on real brand assignments.",
        "course.cta": "Apply now",
        "course.back_to_main": "← Back to main",
        "stats.s1": "Faster than classic shoots",
        "stats.s2": "Travel and crew required",
        "stats.s3": "Iterations and adaptations, no extra cost",
        "stats.s4": "Across all time zones",
        "cta.eyebrow": "Let's work · 11",
        "cta.title": 'Tell us<br>about your <span class="accent">project</span>',
        "cta.sub": "We work with brands around the world. Describe your task — and we'll come back with concept, timeline, and quote within 24 hours.",
        "cta.button": "Send us an email",
        "cta.studio_lbl": "Studio",
        "footer.founded": "Founded by Darkhan Telmanov"
    },
    es: {
        _meta: { title: "MetaFrame — Cine × IA × Marketing", htmlLang: "es", recCity: "Nazarbayev University · Astana" },
        "nav.about": "Sobre", "nav.services": "Servicios", "nav.academy": "Academia", "nav.contacts": "Contacto", "nav.cta": "Solicitar presupuesto →",
        "hero.idx": "Index · 01",
        "hero.tagline": "Cine × IA × Marketing",
        "hero.title": '<span class="line">Producción</span><span class="line">visual <span class="symbol">∞</span></span><span class="line">re<span class="accent">inventada</span></span>',
        "hero.subtitle": 'Cine <span class="accent">×</span> IA <span class="accent">×</span> Marketing — en un único sistema de producción.',
        "hero.cta1": "Ver el trabajo", "hero.cta2": "Hablar del proyecto", "hero.cta3": "Academia", "hero.scroll": "Scroll",
        "founder.eyebrow": "Fundador · 02",
        "founder.title": 'Quién está<br>detrás del <span style="color:var(--cyan); font-style: italic;">cuadro</span>',
        "founder.role": "Fundador · Director Creativo",
        "founder.name": "Darkhan<br>Telmanov",
        "founder.position": "Director de la academia MetaFrame",
        "founder.stat1.lbl": "Experiencia", "founder.stat1.val": "Cine / publicidad / IA",
        "founder.stat2.lbl": "Fue",
        "founder.stat3.val": "El startup de IA con crecimiento más rápido del mundo",
        "founder.stat4.lbl": "Geo",
        "founder.p1": 'MetaFrame es un estudio de producción visual sobre IA generativa. Producimos <strong>spots de marca, creatividades para ads, contenido LED y key&nbsp;visuals</strong> para marcas globales.',
        "founder.p2": 'Fundado por <strong>Darkhan Telmanov</strong>. Anteriormente <span class="highlight">Director Creativo en higgsfield.ai</span>, donde definió el lenguaje visual de un producto que hoy usan millones de creadores y marcas.',
        "founder.p3": 'Combinamos <strong>oficio cinematográfico</strong> — composición, luz, ritmo de montaje — con un <strong>pipeline de producción de ingeniería</strong>. La IA es una herramienta, no un sustituto de la idea.',
        "founder.quote": '«Cualquiera puede generar con IA.<br>Solo unos pocos saben <span style="color:var(--cyan)">dirigirla</span>.»',
        "pillars.eyebrow": "Enfoque · 03", "pillars.meta": "Por qué MetaFrame",
        "pillars.title": 'Tres principios<br>que reescriben las <span style="color:var(--cyan); font-style: italic;">reglas</span>',
        "pillars.lede": "Reescribimos la lógica de la producción audiovisual. Sin viajes, sin actores en rodaje, sin interminables aprobaciones de localización. Solo resultados — muchas veces más rápido.",
        "pillars.p1.title": "Sin presencia física",
        "pillars.p1.text": "Trabajamos con marcas desde cualquier parte del mundo, totalmente en remoto. Sin vuelos, sin scouting, sin equipos reunidos en un solo país. Concepto, producción y entrega final — todo en la nube.",
        "pillars.p2.title": "Escenas reales 1&nbsp;a&nbsp;1 — desde fotos",
        "pillars.p2.text": "¿Quieres recrear tu tienda, producto, fábrica, espacio de evento o tu equipo? Mándanos fotos de calidad y reproduciremos el entorno, los rostros y la identidad de marca con precisión, sin perder reconocimiento.",
        "pillars.p3.title": "10×&nbsp;más rápido que rodar",
        "pillars.p3.text": "Un spot de marca en un día en lugar de dos semanas. Decenas de creatividades para ads pagados en una jornada en vez de un mes. Iteraciones ilimitadas sin costes extra de rodaje, equipo o logística.",
        "clip.tag": "Spots de marca · 16:9",
        "clip.title": 'Spots de<br><span class="accent">marca</span>',
        "clip.desc": "Spots premium para marcas: aperturas de tienda, lanzamientos de producto, piezas de imagen, narrativas corporativas. Lenguaje cinematográfico — sin un solo día de rodaje.",
        "social.tag": "Redes · 9:16 · Creatividades para ads",
        "social.title": 'Formato<br><span class="accent">redes</span>',
        "social.desc": "Reels, TikTok, Shorts, Stories. Creatividades para ads pagados en Meta, TikTok Ads, YouTube Shorts. Producimos decenas de versiones de una misma oferta para A/B testing y escalado de compra de medios.",
        "social.callout": '<span class="strike">Rodar</span><br><span class="accent">Iterar</span><br>al infinito',
        "social.r1.lbl": "Velocidad", "social.r1.val": "10× más rápido que rodar",
        "social.r2.lbl": "Volumen", "social.r2.val": "30+ creatividades / semana",
        "social.r3.lbl": "A/B tests", "social.r3.val": "Sin re-rodajes",
        "social.r4.lbl": "Coste", "social.r4.val": "Desde una jornada estándar de rodaje",
        "social.r5.lbl": "Idiomas", "social.r5.val": "Cualquier mercado y audiencia",
        "poster.tag": "OOH · Pósters · Key visual",
        "poster.title": 'Pósters y<br><span class="accent">key&nbsp;visual</span>',
        "poster.desc": "Banners de gran formato, publicidad exterior, pósters para eventos, portadas de campaña, key visual del año para tu marca. Producimos en cualquier resolución para cualquier formato — desde un flyer hasta una valla en Times Square.",
        "poster.uc1": "Vallas 6×3", "poster.uc2": "Publicidad urbana", "poster.uc3": "Pósters de evento",
        "poster.uc4": "Conciertos / giras", "poster.uc5": "Banners en centros comerciales", "poster.uc6": "Campañas exteriores",
        "poster.uc7": "Portadas para redes", "poster.uc8": "Eventos deportivos", "poster.uc9": "Publicidad en transporte",
        "led.tag": "LED · Escenario · Eventos",
        "led.title": 'Animaciones<br>para el&nbsp;<span class="accent">escenario</span>',
        "led.desc": "Visuales animados para pantallas LED en conciertos, festivales, eventos corporativos, conferencias. Escenas en loop al ritmo del show, loops de imagen de marca, patrones generativos.",
        "led.uc1": "Conciertos", "led.uc2": "Festivales", "led.uc3": "Conferencias", "led.uc4": "Eventos corporativos",
        "led.uc5": "Keynotes", "led.uc6": "Bodas premium", "led.uc7": "Eventos deportivos", "led.uc8": "Pasarela / moda",
        "photo.tag": "Producto · Moda · Lifestyle",
        "photo.title": 'Sets de<br>producto y<br><span class="accent">moda</span>',
        "photo.desc": "Catálogos, lookbooks, imagen lifestyle, contenido para marketplaces. Cualquier localización, cualquier luz, cualquier modelo — sin viajar a un estudio. Mándanos las fotos del producto y entregamos calidad de producción.",
        "ext.eyebrow": "Más · 09", "ext.meta": "Qué más hacemos",
        "ext.title": 'Capacidades<br><span style="color:var(--cyan); font-style: italic;">adicionales</span>',
        "ext.lede": "Más allá de los formatos principales, MetaFrame cubre toda una serie de tareas que muchos clientes descubren solo después de la primera reunión. Si hay un plano por imaginar, encontramos la forma de hacerlo.",
        "ext.i1.t": "Avatares IA / embajadores digitales",
        "ext.i1.d": "Gemelo digital de un CEO, actor o modelo. Entrenado una vez — aparece en decenas de piezas sin estar físicamente.",
        "ext.i2.t": "Videoclips y visuales para artistas",
        "ext.i2.d": "Videoclips completos, teasers, portadas de tema, visuales de streaming. De indie a major.",
        "ext.i3.t": "Contenido para marketplaces",
        "ext.i3.d": "Wildberries, Ozon, Amazon, Wayfair: imágenes principales, infografía, 360°, vídeos de producto, lifestyle.",
        "ext.i4.t": "Logos animados e intros",
        "ext.i4.d": "Brand bumpers, logos en movimiento, intros para YouTube, vídeos corporativos y eventos en directo.",
        "ext.i5.t": "Visualización 3D y arquitectura",
        "ext.i5.d": "Interiores para promotoras, hoteles, restaurantes. Fachadas, exteriores, renders del futuro del espacio.",
        "ext.i6.t": "Localización para nuevos mercados",
        "ext.i6.d": "Una sola creatividad — decenas de versiones adaptadas a idioma, aspecto y cultura. Ideal para campañas internacionales.",
        "ext.i7.t": "Storyboards y pre-visualización",
        "ext.i7.d": "Storyboards y pre-viz para futuros rodajes reales: directores y productores ven cada plano antes de pisar el set.",
        "ext.i8.t": "Packs de contenido por suscripción",
        "ext.i8.d": "«30 reels por semana», «un mes de contenido en un día». La marca recibe un flujo constante de creatividades para producción continua.",
        "course.eyebrow": "Academia · 10",
        "course.meta": "MetaFrame Academy",
        "course.title": 'De cero a <span style="color:var(--cyan);font-style:italic">creador IA</span><br>en 6 semanas',
        "course.lede": "6 módulos, 80% práctica, portfolio real y la oportunidad de entrar en el equipo de MetaFrame.",
        "course.s1": "semanas", "course.s2": "módulos", "course.s3": "práctica / teoría", "course.s4": "primer cliente",
        "course.teaser_cta": "Más información",
        "course.m1.tag": "Fundamentos",
        "course.m1.title": "Del caos de las generaciones a un sistema que da resultado al primer prompt",
        "course.m1.b1": "Dejas de adivinar prompts — empiezas a dirigir el resultado",
        "course.m1.b2": "Entiendes cómo la IA construye sus generaciones y dónde están sus trampas",
        "course.m1.b3": "Eliges la herramienta correcta para cada tarea — sin saltar entre 15 servicios",
        "course.m1.b4": "Lees el trabajo de otros como una radiografía — ves el pipeline, no solo la imagen",
        "course.m2.tag": "Foto · Prompt engineering",
        "course.m2.title": "Una sesión que nunca existió. Un estudio que no existe. Un resultado imposible de distinguir.",
        "course.m2.b1": "Cambias el clima, el objeto, la localización — sin perder el estilo",
        "course.m2.b2": "Generas sesiones de moda sin estudio, sin modelo, sin fotógrafo",
        "course.m2.b3": "Montas fichas de producto para e-commerce indistinguibles de una sesión profesional",
        "course.m2.b4": "Mantienes un personaje en más de 50 cuadros — una cara, un estilo",
        "course.m2.b5": "Diriges la cámara por texto — foco, profundidad de campo, luz, todo por prompt",
        "course.m3.tag": "Vídeo · Guion",
        "course.m3.title": "Animas con un solo prompt lo que antes pedía After Effects y una semana de trabajo",
        "course.m3.b1": "Escribes guiones según la lógica de las redes neuronales — lo que el modelo puede renderizar",
        "course.m3.b2": "Animas escenas complejas: varios objetos, interacción, contacto",
        "course.m3.b3": "Diriges la cámara como un operador — con comandos de texto",
        "course.m3.b4": "Mantienes personaje y localización del primer al último cuadro — sin «drift»",
        "course.m3.b5": "Descompones la acción segundo a segundo en lugar de confiar en la suerte",
        "course.m4.tag": "Diseño de sonido · SFX",
        "course.m4.title": "Sin sonido es una demo. Con sonido es producción. La diferencia — este módulo.",
        "course.m4.b1": "Generas música según el ambiente de la escena — descríbela y la recibes lista",
        "course.m4.b2": "Sincronizas audio con el movimiento de labios en pantalla (lip-sync)",
        "course.m4.b3": "Clonas voces — controlas entonación, pausas, emoción, sin micrófono ni locutor",
        "course.m4.b4": "Quitas el sonido «plástico» de la IA — sala, reverb, fondo — la voz se mete en la escena",
        "course.m4.b5": "Produces tracks completos y remixes de canciones populares",
        "course.m5.tag": "Edición · Color",
        "course.m5.title": "Generar clips puede cualquiera — montarlos en una pieza coherente, muy pocos",
        "course.m5.b1": "Unificas clips de distintos modelos en un mismo estilo — sin saltos de color o contraste",
        "course.m5.b2": "Ajustas timing y ritmo — el montaje deja de sentirse cortado",
        "course.m5.b3": "Con color grading levantas la imagen «plástica» de la IA a un nivel cinematográfico",
        "course.m5.b4": "Eliminas los artefactos de generación en postproducción — el espectador no nota que es IA",
        "course.m5.b5": "Haces upscale a 4K sin perder detalle — Topaz, códecs, ajustes de exportación",
        "course.m6.tag": "Portfolio · Salida al mercado",
        "course.m6.title": "Cierras tu primer cliente en 2 semanas — con oferta, portfolio y guion de venta",
        "course.m6.b1": "Montas 5 piezas para distintos nichos — e-commerce, restaurantes, inmobiliaria, moda, marca personal",
        "course.m6.b2": "Construyes un funnel del primer contacto al pago — mensaje frío, llamada, oferta, cierre",
        "course.m6.b3": "Escribes guiones para chats y llamadas — sabes qué responder a «¿qué me llevo?» y «¿por qué tan caro?»",
        "course.m6.b4": "Empaquetas tu página para que venda por ti",
        "course.method": 'Todos los módulos van <strong>entremezclados desde la primera clase</strong> — el curso está pensado para que practiques desde el principio, te familiarices con la IA y desarrolles tu propio estilo. <strong>80% práctica, 20% teoría.</strong>',
        "course.bonus.tag": "Bonus principal",
        "course.bonus.title": 'Selección para <span style="color:var(--cyan)">MetaFrame</span>',
        "course.bonus.desc": "Buscamos talento. El autor del mejor reel final recibe una oferta de prácticas remuneradas o trabajo por proyecto en nuestro estudio — sobre encargos reales para marcas.",
        "course.cta": "Inscribirme",
        "course.back_to_main": "← A la página principal",
        "stats.s1": "Más rápido que el rodaje clásico",
        "stats.s2": "Viajes y equipos necesarios",
        "stats.s3": "Iteraciones y adaptaciones sin coste extra",
        "stats.s4": "En cualquier zona horaria",
        "cta.eyebrow": "Trabajemos · 11",
        "cta.title": 'Cuéntanos<br>tu <span class="accent">proyecto</span>',
        "cta.sub": "Trabajamos con marcas en todo el mundo. Describe tu necesidad — te respondemos con concepto, plazos y presupuesto en 24 horas.",
        "cta.button": "Enviar un email",
        "cta.studio_lbl": "Estudio",
        "footer.founded": "Fundado por Darkhan Telmanov"
    }
};

function applyLang(lang) {
    if (!T[lang]) lang = "ru";
    const dict = T[lang];
    document.querySelectorAll("[data-i18n]").forEach(el => {
        const k = el.getAttribute("data-i18n");
        if (dict[k] !== undefined) el.textContent = dict[k];
    });
    document.querySelectorAll("[data-i18n-html]").forEach(el => {
        const k = el.getAttribute("data-i18n-html");
        if (dict[k] !== undefined) el.innerHTML = dict[k];
    });
    document.documentElement.lang = dict._meta.htmlLang;
    document.title = dict._meta.title;
    document.querySelectorAll(".lang-btn").forEach(b => {
        b.classList.toggle("active", b.dataset.lang === lang);
    });
    window._recCity = dict._meta.recCity;
    try { localStorage.setItem("metaframe_lang", lang); } catch (e) {}
}

(function initLang() {
    let saved = null;
    try { saved = localStorage.getItem("metaframe_lang"); } catch (e) {}
    let lang = saved;
    if (!lang) {
        const nav = (navigator.language || "ru").slice(0, 2).toLowerCase();
        lang = T[nav] ? nav : "ru";
    }
    applyLang(lang);
    document.querySelectorAll(".lang-btn").forEach(b => {
        b.addEventListener("click", () => applyLang(b.dataset.lang));
    });
})();

const io = new IntersectionObserver((entries) => {
    entries.forEach(e => {
        if (e.isIntersecting) {
            e.target.classList.add("in");
            io.unobserve(e.target);
        }
    });
}, { threshold: 0.12, rootMargin: "0px 0px -60px 0px" });
document.querySelectorAll(".reveal").forEach(el => io.observe(el));

window.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll(".hero .reveal").forEach((el, i) => {
        setTimeout(() => el.classList.add("in"), 100 + i * 120);
    });
});

(function () {
    const indicator = document.querySelector(".rec-indicator .rec-text");
    if (!indicator) return;
    const start = Date.now();
    function tick() {
        const t = Math.floor((Date.now() - start) / 1000);
        const h = String(Math.floor(t / 3600)).padStart(2, "0");
        const m = String(Math.floor(t / 60) % 60).padStart(2, "0");
        const s = String(t % 60).padStart(2, "0");
        const city = window._recCity || "Nazarbayev University · Astana";
        indicator.textContent = "REC · " + h + ":" + m + ":" + s + " · " + city;
        requestAnimationFrame(tick);
    }
    tick();
})();
